name: jportfolio_web
description: A new Jaspr project
version: 0.0.1

publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.0
  jaspr_router: ^0.8.1
  serverpod_auth_client: ^3.1.1
  backend_client:
    path: ../../packages/client
  shared:
    path: ../../packages/shared

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.0
  lints: ^5.0.0

jaspr:
  mode: static
  port: 3000
